# Created with package:mono_repo v2.1.0
language: dart

# Custom configuration
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: 2.4.0; PKGS: validations, validations_generator; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings lib test`]"
      dart: "2.4.0"
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh dartfmt dartanalyzer
    - stage: unit_test
      name: "SDK: 2.4.0; PKG: validations; TASKS: `pub run test lib/**/*.spec.dart`"
      dart: "2.4.0"
      env: PKGS="validations"
      script: ./tool/travis.sh test_0
    - stage: unit_test
      name: "SDK: 2.4.0; PKG: validations_generator; TASKS: `pub run test`"
      dart: "2.4.0"
      env: PKGS="validations_generator"
      script: ./tool/travis.sh test_1

stages:
  - analyzer_and_format
  - unit_test

cache:
  directories:
    - "$HOME/.pub-cache"
    - validations/.dart_tool/build
    - validations_generator/.dart_tool/build
