name: validations
description: Validations for dart models.
version: 1.0.0
homepage: https://github.com/dartling/validations.git
author: Rob Halff <rob.halff@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  validators: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
