name: validator_example
version: 1.0.0
description: Validator example
authors:
  - Rob Halff <rob.halff@gmail.com>
homepage: https://github.com/dartling/validator.git

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  validations:
    path: ../../validations

dev_dependencies:
  pedantic: ^1.0.0
  build_runner: ^1.5.0
  validations_generator:
    path: ../
