# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.4.0

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings lib test
    dart: [2.4.0]
- unit_test:
  - test
  - command: pub run build_runner test --delete-conflicting-outputs -- -p chrome
- ensure_build:
  - test: --run-skipped -t presubmit-only test/ensure_build_test.dart

cache:
  directories:
  - .dart_tool/build
