name: validations_generator
version: 1.0.0
description: Validator built using source_gen
authors:
- Rob Halff <rob.halff@gmail.com>
homepage: https://github.com/dartling/validator.git

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  validations:
    path: ../validations
  analyzer: ^0.36.4
  build: ^1.1.4
  logging: ^0.11.3+2
  source_gen: ^0.9.4+2
  code_builder: ^3.2.0
  dart_style: ^1.2.8
  meta: ^1.0.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.4
  build_runner: ^1.6.1
  build_web_compilers: ^2.1.2
  build_test: ^0.10.8
  collection: ^1.14.11
